import{OUTREACH_STATUSES,COLLABORATION_STAGES,FIT_VERDICTS,TIERS,ACCOUNT_TYPES,DOG_SIZES,RELATIONSHIPS,SHIPMENT_STATUSES,DELIVERABLE_STATUSES,PUBLICATION_STATUSES,RIGHTS_STATUSES,PAYMENT_STATUSES,DEFAULT_PAGE_SIZE,PAGE_SIZES,badgeClass}from'./constants.js?v=20260812-delete2';
import{dataMode,creatorPage,collaborationPage,creatorChoices,related,getOne,save,archive,referenceData,createCollaborationFromOutreach,cancelCollaboration,deleteErroneousCollaboration,bulkUpdateCreators,logActivity,syncCollaborationProducts,dashboardCounts,exportCreatorResults,exportCollaborationResults}from'./data.js?v=20260812-delete2';

const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const state={view:'dashboard',creators:[],creatorCount:0,creatorPage:1,creatorPageSize:DEFAULT_PAGE_SIZE,creatorFilters:{},creatorSelection:new Set(),collaborations:[],collaborationCount:0,collaborationPage:1,collaborationPageSize:DEFAULT_PAGE_SIZE,collaborationFilters:{},refs:{owners:[],campaigns:[],products:[],creatorOptions:[]},drawer:null,drawerTab:'profile',request:{creator:0,collaboration:0,detail:0,drawerRender:0}};
let toastTimer;

boot();
async function boot(){bindStatic();$('#environmentBadge').textContent=dataMode==='demo'?'Demo 1,000':'Live';return openApp()}
function bindStatic(){
  $$('.nav-button').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
  $$('[data-go]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.go)));
  $('#refreshBtn').addEventListener('click',refreshView);$$('[data-close-drawer]').forEach(el=>el.addEventListener('click',closeDrawer));
  $('#newCreatorBtn').addEventListener('click',()=>openCreatorEditor({}));$('#newCollaborationBtn').addEventListener('click',()=>openCollaborationEditor({}));
  bindFilters('#creatorFilters','creator');bindFilters('#collaborationFilters','collaboration');
  $('#selectPageBtn').addEventListener('click',()=>{state.creators.forEach(row=>state.creatorSelection.add(row.id));renderCreators()});
  $('#clearSelectionBtn').addEventListener('click',()=>{state.creatorSelection.clear();renderCreators()});
  $('#bulkCreatorBtn').addEventListener('click',()=>{if(!state.creatorSelection.size)return toast('Select at least one creator.');$('#bulkDialog').showModal()});
  $('#applyBulkBtn').addEventListener('click',applyBulkUpdate);$('#exportCreatorsBtn').addEventListener('click',exportCreators);$('#exportCollaborationsBtn').addEventListener('click',exportCollaborations);
}
async function openApp(){$('#app').classList.remove('hidden');setStatus('Loading');try{state.refs={...await referenceData(),creatorOptions:[]};fillStaticOptions();await loadDashboard();setStatus('Ready')}catch(error){handleError(error)}}
function setView(view){state.view=view;$$('.nav-button').forEach(button=>button.classList.toggle('active',button.dataset.view===view));$$('.view').forEach(panel=>panel.classList.toggle('active',panel.id===`${view}View`));$('#pageTitle').textContent={dashboard:'Dashboard',creators:'Creators',collaborations:'Collaborations'}[view];if(view==='dashboard')loadDashboard();if(view==='creators')loadCreators();if(view==='collaborations')loadCollaborations()}
function refreshView(){setStatus('Refreshing');return({dashboard:loadDashboard,creators:loadCreators,collaborations:loadCollaborations}[state.view]||loadDashboard)().finally(()=>setStatus('Ready'))}
function fillStaticOptions(){
  setOptions($('#creatorFilters [name=outreach_status]'),OUTREACH_STATUSES);setOptions($('#creatorFilters [name=fit_verdict]'),FIT_VERDICTS);setOptions($('#creatorFilters [name=tier]'),TIERS);setOptions($('#creatorFilters [name=account_type]'),ACCOUNT_TYPES);setOptions($('#creatorFilters [name=dog_size]'),DOG_SIZES);setOptions($('#creatorFilters [name=owner_id]'),state.refs.owners.map(x=>[x.id,x.name]));
  setOptions($('#collaborationFilters [name=stage]'),COLLABORATION_STAGES);setOptions($('#collaborationFilters [name=campaign_id]'),state.refs.campaigns.map(x=>[x.id,x.name]));setOptions($('#collaborationFilters [name=product_id]'),state.refs.products.map(x=>[x.id,`${x.name} · ${x.sku}`]));setOptions($('#collaborationFilters [name=owner_id]'),state.refs.owners.map(x=>[x.id,x.name]));
  setOptions($('#bulkOwner'),state.refs.owners.map(x=>[x.id,x.name]));setOptions($('#bulkFit'),FIT_VERDICTS);setOptions($('#bulkRelationship'),RELATIONSHIPS);
}
function bindFilters(selector,type){const root=$(selector);let timer;root.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>readFilters(root,type),300)});root.addEventListener('change',()=>readFilters(root,type));$('.clear-filters',root).addEventListener('click',()=>{$$('input,select',root).forEach(input=>input.value='');readFilters(root,type)})}
function readFilters(root,type){const filters=Object.fromEntries(new FormDataLike(root));if(type==='creator'){state.creatorFilters=filters;state.creatorPage=1;loadCreators()}else{state.collaborationFilters=filters;state.collaborationPage=1;loadCollaborations()}}
function FormDataLike(root){return $$('input,select',root).map(input=>[input.name,input.value])}
async function exportCreators(){const{search='',...filters}=state.creatorFilters;setStatus('Exporting creators');try{const count=await exportCreatorResults({search,filters,sort:'updated_at.desc'});toast(`Exported ${count} creators`)}catch(error){handleError(error)}finally{setStatus('Ready')}}
async function exportCollaborations(){const{search='',...filters}=state.collaborationFilters;setStatus('Exporting collaborations');try{const count=await exportCollaborationResults({search,filters,sort:'updated_at.desc'});toast(`Exported ${count} collaborations`)}catch(error){handleError(error)}finally{setStatus('Ready')}}
async function loadDashboard(){try{const counts=await dashboardCounts();renderDashboard(counts)}catch(error){handleError(error)}}
function renderDashboard(c){
  const rates=[['Reply',c.rates.reply,'Replied creators / creators contacted'],['Collaboration',c.rates.collaboration,'Confirmed collaborations / creators who replied'],['Shipping',c.rates.shipping,'Shipped or delivered / confirmed collaborations'],['Post',c.rates.post,'Published / confirmed collaborations']];
  $('#dashboardCards').innerHTML=rates.map(([label,rate,definition])=>`<article class="metric-card rate-card"><span>${esc(label)}</span><strong>${rate.percent}%</strong><small class="metric-fraction">${rate.numerator}/${rate.denominator}</small><p>${esc(definition)}</p></article>`).join('');
  const activeRates=rates.filter(([,rate])=>rate.denominator>0),bottleneck=activeRates.sort((a,b)=>a[1].percent-b[1].percent)[0];
  $('#bottleneckNote').innerHTML=bottleneck?`<strong>Current bottleneck: ${esc(bottleneck[0])} ${bottleneck[1].percent}%</strong><span>${bottleneck[1].denominator-bottleneck[1].numerator} records have not moved through this step yet.</span>`:'<span>Add outreach and collaboration activity to reveal the current bottleneck.</span>';
  $('#outreachTasks').innerHTML=taskRows([['Not contacted',c.notContacted],['Follow-up due',c.followUps],['Negotiating',c.negotiating]]);
  $('#collaborationTasks').innerHTML=taskRows([['DM owner · confirm products + address',c.awaitingDetails],['Fulfillment · pack + add tracking',c.ready],['In transit',c.shipped],['Delivered · waiting for post',c.deliveredPendingPost]]);
  const max=Math.max(1,...c.pipeline.map(([,value])=>value));
  $('#creatorProgress').innerHTML=c.pipeline.map(([label,value])=>`<div class="pipeline-row"><span>${esc(label)}</span><div class="pipeline-track"><i style="width:${Math.round(value/max*100)}%"></i></div><strong>${value}</strong></div>`).join('');
  $('#productMix').innerHTML=c.productMix.length?c.productMix.map(([name,value])=>`<div class="product-mix-row"><span>${esc(name)}</span><strong>${value}</strong></div>`).join(''):'<div class="empty-state compact-empty">No final products assigned yet.</div>';
}
function taskRows(rows){return rows.map(([label,value])=>`<div class="task-row"><span>${esc(label)}</span><strong>${value}</strong></div>`).join('')}
async function loadCreators(){const token=++state.request.creator;setStatus('Loading creators');try{const{search='',...filters}=state.creatorFilters;const result=await creatorPage({page:state.creatorPage,pageSize:state.creatorPageSize,search,filters,sort:'updated_at.desc'});if(token!==state.request.creator)return;state.creators=result.data;state.creatorCount=result.count;renderCreators();setStatus(`${result.count} creators`)}catch(error){handleError(error)}}
function renderCreators(){
  $('#creatorRows').innerHTML=state.creators.length?state.creators.map(row=>{const account=row.creator_accounts?.find(x=>x.is_primary)||row.creator_accounts?.[0]||{handle:row.primary_handle,platform:row.primary_platform,profile_url:row.primary_profile_url};const outreach=row.outreach_records?.[0]||{status:row.outreach_status,last_contact_at:row.last_contact_at};const profile=creatorProfileUrl(account?.profile_url,account?.handle||row.nickname,account?.platform);return`<tr data-id="${row.id}"><td><input class="creator-check" type="checkbox" ${state.creatorSelection.has(row.id)?'checked':''}></td><td class="creator-cell"><strong>${esc(row.display_name||row.nickname||'Unnamed')}</strong><small>${esc(row.creator_code||'')} · ${esc(row.location||'No location')}</small></td><td><strong>${esc(account?.handle?`@${account.handle}`:'—')}</strong><br><small class="muted">${esc(account?.platform||'')}</small></td><td><span class="badge ${badgeClass(row.fit_verdict)}">${esc(row.fit_verdict||'Not rated')}</span></td><td><span class="badge ${badgeClass(outreach?.status)}">${esc(outreach?.status||'Not Contacted')}</span></td><td>${esc(ownerName(row.owner_id))}</td><td>${date(outreach?.last_contact_at)}</td><td>${row.collaboration_count||row.collaborations?.length||0}</td><td><div class="row-actions"><button class="secondary compact open-row" type="button">Open</button><button class="secondary compact new-order-row" type="button" title="Create a confirmed collaboration for this creator">+ Order</button>${profileAction(profile)}</div></td></tr>`}).join(''):'<tr><td colspan="9"><div class="empty-state">No creators match these filters.</div></td></tr>';
  $$('#creatorRows tr[data-id]').forEach(tr=>{const id=tr.dataset.id,row=state.creators.find(item=>item.id===id);$('.creator-check',tr).addEventListener('click',event=>{event.stopPropagation();event.target.checked?state.creatorSelection.add(id):state.creatorSelection.delete(id);renderSelectionCount()});$('.open-row',tr).addEventListener('click',()=>openCreator(id));$('.new-order-row',tr).addEventListener('click',event=>{event.stopPropagation();if(!confirm('Create an order only after this creator has explicitly confirmed the collaboration. Continue?'))return;openCollaborationEditor({creator_id:id,owner_id:row?.owner_id||null,type:'Seeding',stage:COLLABORATION_STAGES[0],is_repeat:Boolean(row?.collaboration_count||row?.collaborations?.length)})});bindProfileLinks(tr);tr.addEventListener('dblclick',()=>openCreator(id))});renderSelectionCount();renderPagination('creator')
}
function renderSelectionCount(){$('#creatorSelectionCount').textContent=`${state.creatorSelection.size} selected`}
async function loadCollaborations(){const token=++state.request.collaboration;setStatus('Loading collaborations');try{const{search='',...filters}=state.collaborationFilters;const result=await collaborationPage({page:state.collaborationPage,pageSize:state.collaborationPageSize,search,filters,sort:'updated_at.desc'});if(token!==state.request.collaboration)return;state.collaborations=result.data;state.collaborationCount=result.count;renderCollaborations();setStatus(`${result.count} collaborations`)}catch(error){handleError(error)}}
function renderCollaborations(){
  $('#collaborationCount').textContent=`${state.collaborationCount} collaboration records`;$('#collaborationRows').innerHTML=state.collaborations.length?state.collaborations.map(row=>{const products=row.product_names||row.collaboration_products?.map(x=>x.product?.name).filter(Boolean).join(', ')||'Not assigned';const completed=row.deliverables_completed??row.deliverables?.filter(x=>['Approved','Published'].includes(x.status)).length??0;const total=row.deliverables_total??row.deliverables?.length??0;const profile=creatorProfileUrl(row.creator_profile_url||row.creator_account?.profile_url||row.creator?.primary_profile_url,row.creator_handle||row.creator_account?.handle||row.creator?.nickname,'Instagram');return`<tr data-id="${row.id}"><td class="creator-cell"><strong>${esc(row.collaboration_code||shortId(row.id,'CO'))}</strong><small>${esc(row.collaboration_name||row.type||'Seeding')}</small></td><td>${esc(row.creator_name||row.creator?.display_name||row.creator?.nickname||'Unknown')}</td><td>${esc(row.campaign_name||row.campaign?.name||'—')}</td><td><span class="badge ${badgeClass(row.stage)}">${esc(row.stage)}</span></td><td>${esc(products)}</td><td>${completed}/${total}</td><td>${date(row.due_date)}</td><td>${esc(ownerName(row.owner_id))}</td><td><div class="row-actions"><button class="secondary compact open-row" type="button">Open</button>${row.stage==='Closed'?'<button class="danger-button compact delete-error-row" type="button">Delete</button>':''}${profileAction(profile)}</div></td></tr>`}).join(''):'<tr><td colspan="9"><div class="empty-state">No collaborations match these filters.</div></td></tr>';
  $$('#collaborationRows tr[data-id]').forEach(tr=>{$('.open-row',tr).addEventListener('click',()=>openCollaboration(tr.dataset.id));$('.delete-error-row',tr)?.addEventListener('click',event=>{event.stopPropagation();deleteErroneousRecord(tr.dataset.id)});bindProfileLinks(tr);tr.addEventListener('dblclick',()=>openCollaboration(tr.dataset.id))});renderPagination('collaboration')
}
function renderPagination(type){const isCreator=type==='creator',page=isCreator?state.creatorPage:state.collaborationPage,size=isCreator?state.creatorPageSize:state.collaborationPageSize,count=isCreator?state.creatorCount:state.collaborationCount,root=$(`#${type}Pagination`),pages=Math.max(1,Math.ceil(count/size));root.innerHTML=`<span class="muted">Page ${page} of ${pages} · ${count} records</span><select aria-label="Rows per page">${PAGE_SIZES.map(n=>`<option ${n===size?'selected':''}>${n}</option>`).join('')}</select><button class="secondary compact prev" ${page<=1?'disabled':''}>Previous</button><button class="secondary compact next" ${page>=pages?'disabled':''}>Next</button>`;$('.prev',root).addEventListener('click',()=>changePage(type,-1));$('.next',root).addEventListener('click',()=>changePage(type,1));$('select',root).addEventListener('change',event=>{if(isCreator){state.creatorPageSize=Number(event.target.value);state.creatorPage=1;loadCreators()}else{state.collaborationPageSize=Number(event.target.value);state.collaborationPage=1;loadCollaborations()}})}
function changePage(type,delta){if(type==='creator'){state.creatorPage+=delta;loadCreators()}else{state.collaborationPage+=delta;loadCollaborations()}}

async function openCreator(id){const token=++state.request.detail;state.drawer=null;openDrawer('Creator','Loading…','');clearDrawerContent('Loading creator…');try{const creator=await getOne('creators',id);if(token!==state.request.detail)return;if(!creator)throw new Error('Creator not found.');state.drawer={type:'creator',record:creator};state.drawerTab='profile';renderCreatorDrawer()}catch(error){if(token===state.request.detail){clearDrawerContent('Unable to load this creator.');handleError(error)}}}
function openCreatorEditor(record){state.drawer={type:'creator',record};state.drawerTab='profile';openDrawer('Creator',record.display_name||'New creator','');renderCreatorDrawer(true)}
async function renderCreatorDrawer(editing=false){if(state.drawer?.type!=='creator')return;const renderToken=++state.request.drawerRender,c=state.drawer.record,expectedId=c.id,expectedTab=state.drawerTab;openDrawer('Creator',c.display_name||c.nickname||'New creator',c.creator_code||'');renderTabs([['profile','Profile'],['accounts','Accounts & Pets'],['outreach','Outreach'],['collaborations','Collaborations']],state.drawerTab,tab=>{state.drawerTab=tab;renderCreatorDrawer(editing)});const body=$('#drawerBody');body.innerHTML='<div class="empty-state">Loading…</div>';$('#drawerFooter').innerHTML='';try{if(state.drawerTab==='profile')body.innerHTML=creatorProfileForm(c,editing);else if(state.drawerTab==='accounts')await renderCreatorRelations(c.id,body);else if(state.drawerTab==='outreach')await renderOutreach(c.id,body);else await renderCreatorCollaborations(c.id,body);if(renderToken!==state.request.drawerRender||!activeDrawer('creator',expectedId,expectedTab))return;renderDrawerFooter(c,editing,'creator');bindDrawerForms()}catch(error){if(renderToken===state.request.drawerRender&&activeDrawer('creator',expectedId,expectedTab)){body.innerHTML='<div class="empty-state">Unable to load this section.</div>';handleError(error)}}}
function creatorProfileForm(c,editing){return`<div class="drawer-section"><h3>Core identity</h3><div class="form-grid">${field('display_name','Display Name',c.display_name,editing)}${field('nickname','Nickname / Handle',c.nickname,editing)}${field('legal_name','Legal Name',c.legal_name,editing)}${field('contact_email','Email',c.contact_email,editing,'email')}${field('contact_phone','Phone',c.contact_phone,editing)}${selectField('tier','Tier',TIERS,c.tier,editing)}${selectField('fit_verdict','Fit Verdict',FIT_VERDICTS,c.fit_verdict,editing)}${selectField('account_type','Account Type',ACCOUNT_TYPES,c.account_type,editing)}${selectField('dog_size','Dog Size',DOG_SIZES,c.dog_size,editing)}${selectField('relationship_status','Relationship',RELATIONSHIPS,c.relationship_status,editing)}${selectField('owner_id','Owner',state.refs.owners.map(x=>[x.id,x.name]),c.owner_id,editing)}${field('location','Location',c.location,editing)}${field('tags','Tags',Array.isArray(c.tags)?c.tags.join(', '):c.tags,editing)}${textarea('fit_notes','Fit Notes',c.fit_notes,editing)}${textarea('notes','Notes',c.notes,editing)}${textarea('database_notes','Database Notes',c.database_notes,editing)}</div></div>`}
async function renderCreatorRelations(id,body){if(!id)return body.innerHTML='<div class="empty-state">Save the creator before adding accounts, pets or addresses.</div>';const[accounts,pets,addresses]=await Promise.all([related('creator_accounts','creator_id',id),related('creator_pets','creator_id',id),related('creator_addresses','creator_id',id)]);if(!activeDrawer('creator',id,'accounts'))return;body.innerHTML=creatorRelationSection('creator_accounts','Social Accounts',accounts,row=>`${row.platform}: @${row.handle}`,row=>row.profile_url)+creatorRelationSection('creator_pets','Pets',pets,row=>`${row.name||'Pet'} · ${row.breed||'Unknown breed'}`,row=>`${row.size||''} ${row.neck_size_cm?`· ${row.neck_size_cm} cm neck`:''}`)+creatorRelationSection('creator_addresses','Addresses',addresses,row=>row.label||'Address',row=>row.full_address);for(const[table,rows]of[['creator_accounts',accounts],['creator_pets',pets],['creator_addresses',addresses]]){$$(`[data-add-creator-related="${table}"]`).forEach(button=>button.addEventListener('click',()=>openCreatorRelationEditor(table,{})));$$(`[data-edit-creator-related="${table}"]`).forEach(button=>button.addEventListener('click',()=>openCreatorRelationEditor(table,rows.find(row=>row.id===button.dataset.id)||{})))}}
function creatorRelationSection(table,title,rows,primary,secondary){return`<div class="drawer-section"><div class="section-head"><h3>${title}</h3><button class="secondary compact" data-add-creator-related="${table}" type="button">Add</button></div>${rows.length?rows.map(row=>`<article class="related-item"><div><strong>${esc(primary(row)||'Untitled')}</strong><p>${esc(secondary(row)||'')}</p></div><button class="secondary compact" data-edit-creator-related="${table}" data-id="${row.id}" type="button">Edit</button></article>`).join(''):`<div class="empty-state">No ${title.toLowerCase()} yet.</div>`}</div>`}
function openCreatorRelationEditor(table,record){const title={creator_accounts:'Social Account',creator_pets:'Pet',creator_addresses:'Address'}[table],body=$('#drawerBody');body.innerHTML=`<div class="drawer-section"><div class="section-head"><h3>${record.id?'Edit':'Add'} ${title}</h3><button id="cancelCreatorRelated" class="secondary compact" type="button">Cancel</button></div><div id="creatorRelatedForm" class="form-grid">${creatorRelationFields(table,record)}</div><div class="editor-actions"><button id="saveCreatorRelated" type="button">Save ${title}</button>${record.id?'<button id="archiveCreatorRelated" class="secondary" type="button">Archive</button>':''}</div></div>`;$('#cancelCreatorRelated').addEventListener('click',()=>renderCreatorDrawer());$('#saveCreatorRelated').addEventListener('click',()=>saveCreatorRelation(table,record));$('#archiveCreatorRelated')?.addEventListener('click',async()=>{if(!confirm(`Archive this ${title.toLowerCase()}?`))return;await archive(table,record.id);await logActivity({entityType:table,entityId:record.id,creatorId:state.drawer.record.id,action:'Archived',before:record});renderCreatorDrawer();toast(`${title} archived`)})}
function creatorRelationFields(table,r){if(table==='creator_accounts')return`${field('platform','Platform',r.platform||'Instagram',true)}${field('handle','Handle',r.handle,true)}${field('profile_url','Profile URL',r.profile_url,true,'url')}${field('followers','Followers',r.followers,true,'number')}${field('engagement_rate','Engagement Rate',r.engagement_rate,true,'number')}${selectField('is_primary','Primary Account',[['false','No'],['true','Yes']],String(Boolean(r.is_primary)),true,false)}${field('link_status','Link Status',r.link_status,true)}`;if(table==='creator_pets')return`${field('name','Pet Name',r.name,true)}${field('breed','Breed',r.breed,true)}${selectField('size','Dog Size',DOG_SIZES,r.size,true)}${field('neck_size_cm','Neck Size (cm)',r.neck_size_cm,true,'number')}${field('weight_kg','Weight (kg)',r.weight_kg,true,'number')}${textarea('fit_notes','Fit Notes',r.fit_notes,true)}`;return`${field('label','Label',r.label||'Shipping address',true)}${field('recipient_name','Recipient Name',r.recipient_name,true)}${field('phone','Phone',r.phone,true)}${field('country','Country',r.country||'United States',true)}${selectField('is_default','Default Address',[['false','No'],['true','Yes']],String(Boolean(r.is_default)),true,false)}${textarea('full_address','Full Address',r.full_address,true)}`}
async function saveCreatorRelation(table,before){const payload=Object.fromEntries(FormDataLike($('#creatorRelatedForm')));for(const key of ['followers','engagement_rate','neck_size_cm','weight_kg'])if(payload[key]!=='')payload[key]=Number(payload[key]);for(const key of ['is_primary','is_default'])if(key in payload)payload[key]=payload[key]==='true';const creator=state.drawer.record,saved=await save(table,{...before,...payload,creator_id:creator.id,owner_id:creator.owner_id||null});await logActivity({entityType:table,entityId:saved.id,creatorId:creator.id,action:before.id?'Updated':'Created',before:before.id?before:null,after:saved});toast('Saved');renderCreatorDrawer()}
async function renderOutreach(id,body){if(!id)return body.innerHTML='<div class="empty-state">Save the creator first.</div>';const rows=await related('outreach_records','creator_id',id);if(!activeDrawer('creator',id,'outreach'))return;body.innerHTML=`<div class="drawer-section"><div class="section-head"><h3>Outreach history</h3><button id="addOutreachBtn" class="secondary compact" type="button">Add touch</button></div>${rows.length?rows.map(row=>`<article class="related-item"><div><strong>${esc(row.status)}</strong><p>${esc(row.channel||'')} · ${date(row.last_contact_at)}</p><p>${esc(row.notes||'')}</p></div></article>`).join(''):'<div class="empty-state">No outreach recorded.</div>'}</div>`;$('#addOutreachBtn')?.addEventListener('click',()=>openOutreachEditor(id))}
async function renderCreatorCollaborations(id,body){if(!id)return body.innerHTML='<div class="empty-state">Save the creator first.</div>';const rows=await related('collaborations','creator_id',id);if(!activeDrawer('creator',id,'collaborations'))return;body.innerHTML=`<div class="drawer-section"><div class="section-head"><h3>Collaboration history</h3><button id="convertCreatorBtn" class="compact" type="button">Create confirmed collaboration</button></div>${rows.length?rows.map(row=>`<article class="related-item"><div><strong>${esc(row.collaboration_code||shortId(row.id,'CO'))}</strong><p><span class="badge ${badgeClass(row.stage)}">${esc(row.stage)}</span> · ${date(row.start_date)}</p></div><button class="secondary compact" data-open-collab="${row.id}">Open</button></article>`).join(''):'<div class="empty-state">No collaboration. Create one only after the creator explicitly agrees.</div>'}</div>`;$('#convertCreatorBtn')?.addEventListener('click',async()=>{if(!confirm('Create a collaboration only after the creator has explicitly agreed. Has this creator confirmed the collaboration?'))return;await createCollaborationFromOutreach(id,state.drawer.record.owner_id);toast('Confirmed collaboration created.');renderCreatorDrawer()});$$('[data-open-collab]').forEach(button=>button.addEventListener('click',()=>openCollaboration(button.dataset.openCollab)))}
function renderDrawerFooter(record,editing,type){const footer=$('#drawerFooter');if(editing)footer.innerHTML=`<button class="secondary cancel-edit" type="button">Cancel</button><button class="save-record" type="button">Save</button>`;else if(type==='collaboration')footer.innerHTML=`<button class="secondary edit-record" type="button">Edit</button>${record.stage==='Closed'?`<button class="danger-button delete-erroneous" type="button">Delete erroneous record</button>`:`<button class="danger-button cancel-collaboration" type="button">Cancel collaboration</button>`}`;else footer.innerHTML=`<button class="secondary edit-record" type="button">Edit</button><button class="secondary archive-record" type="button">Archive</button>`;$('.edit-record',footer)?.addEventListener('click',()=>type==='creator'?openCreatorEditor(record):openCollaborationEditor(record));$('.cancel-edit',footer)?.addEventListener('click',()=>type==='creator'?openCreator(record.id):openCollaboration(record.id));$('.save-record',footer)?.addEventListener('click',()=>saveDrawer(type));$('.cancel-collaboration',footer)?.addEventListener('click',()=>cancelCollaborationRecord(record));$('.delete-erroneous',footer)?.addEventListener('click',()=>deleteErroneousRecord(record.id));$('.archive-record',footer)?.addEventListener('click',async()=>{if(!confirm('Archive this creator? It can be restored from the database.'))return;await archive('creators',record.id);closeDrawer();refreshView();toast('Archived')})}
async function cancelCollaborationRecord(record){const reason=prompt('Why is this collaboration being cancelled? This reason will be saved in its history.','Created by mistake');if(reason===null)return;if(!reason.trim())return toast('Enter a cancellation reason.');const shipments=await related('shipments','collaboration_id',record.id),sent=shipments.some(row=>['Shipped','Delivered'].includes(row.status));const warning=sent?'A shipment is already marked as sent. Cancelling will preserve the shipment record but remove this collaboration from active metrics and queues. Continue?':'Cancel this collaboration? It will remain in history but leave active metrics, product counts, and fulfillment queues.';if(!confirm(warning))return;const saved=await cancelCollaboration(record,reason);state.drawer.record=saved;await refreshView();renderCollaborationDrawer();toast('Collaboration cancelled and retained in history.')}
async function deleteErroneousRecord(id){try{const record=await getOne('collaborations',id);if(!record)return toast('This collaboration no longer exists.');if(record.stage!=='Closed')return toast('Cancel the collaboration before permanently deleting it.');const code=record.collaboration_code||shortId(record.id,'CO'),reason=prompt(`Delete ${code} permanently?\n\nEnter the deletion reason to continue:`,'Created by mistake');if(reason===null)return;if(!reason.trim())return toast('Enter a deletion reason.');setStatus('Deleting erroneous record');await deleteErroneousCollaboration(record,reason);if(state.drawer?.record?.id===id)closeDrawer();await refreshView();setStatus('Ready');toast(`${code} permanently deleted.`)}catch(error){handleError(error)}}
async function saveDrawer(type){const form=$('#drawerBody');const payload=Object.fromEntries(FormDataLike(form));if(payload.tags)payload.tags=payload.tags.split(',').map(x=>x.trim()).filter(Boolean);if(type==='collaboration'){if(!payload.creator_id)return toast('Choose a creator before saving.');payload.is_repeat=payload.is_repeat==='true';if(payload.approved_budget==='')payload.approved_budget=null}const table=type==='creator'?'creators':'collaborations',before=state.drawer.record?.id?{...state.drawer.record}:null;const record=await save(table,{...state.drawer.record,...payload});await logActivity({entityType:type,entityId:record.id,creatorId:type==='creator'?record.id:record.creator_id,collaborationId:type==='collaboration'?record.id:null,action:before?'Updated':'Created',before,after:record});state.drawer.record=record;toast('Saved');type==='creator'?openCreator(record.id):openCollaboration(record.id);refreshView()}

async function openCollaboration(id){const token=++state.request.detail;state.drawer=null;openDrawer('Collaboration','Loading…','');clearDrawerContent('Loading collaboration…');try{const c=await getOne('collaborations',id);if(token!==state.request.detail)return;if(!c)throw new Error('Collaboration not found.');if(c.creator_id&&!state.refs.creatorOptions.some(row=>row.id===c.creator_id)){const creator=await getOne('creators',c.creator_id);if(token!==state.request.detail)return;if(creator)state.refs.creatorOptions.push(creator)}state.drawer={type:'collaboration',record:c};state.drawerTab='overview';renderCollaborationDrawer()}catch(error){if(token===state.request.detail){clearDrawerContent('Unable to load this collaboration.');handleError(error)}}}
async function openCollaborationEditor(record){state.drawer={type:'collaboration',record};state.drawerTab='overview';openDrawer('Collaboration',record.collaboration_code||'New collaboration','');$('#drawerBody').innerHTML='<div class="empty-state">Loading creator choices…</div>';try{state.refs.creatorOptions=await creatorChoices();renderCollaborationDrawer(true)}catch(error){handleError(error)}}
async function renderCollaborationDrawer(editing=false){if(state.drawer?.type!=='collaboration')return;const renderToken=++state.request.drawerRender,c=state.drawer.record,expectedId=c.id,expectedTab=state.drawerTab;openDrawer('Collaboration',c.collaboration_code||shortId(c.id,'CO')||'New collaboration',c.collaboration_name||'Confirmed work');renderTabs([['overview','Overview'],['products','Products'],['deliverables','Deliverables'],['shipments','Shipments'],['content','Publications & Assets'],['activity','Activity']],state.drawerTab,tab=>{state.drawerTab=tab;renderCollaborationDrawer(editing)});const body=$('#drawerBody');body.innerHTML='<div class="empty-state">Loading…</div>';$('#drawerFooter').innerHTML='';try{if(state.drawerTab==='overview')body.innerHTML=collaborationForm(c,editing);else if(!c.id)body.innerHTML='<div class="empty-state">Save the collaboration before adding related records.</div>';else await renderCollaborationRelations(c,state.drawerTab,body);if(renderToken!==state.request.drawerRender||!activeDrawer('collaboration',expectedId,expectedTab))return;renderDrawerFooter(c,editing,'collaboration');bindDrawerForms()}catch(error){if(renderToken===state.request.drawerRender&&activeDrawer('collaboration',expectedId,expectedTab)){body.innerHTML='<div class="empty-state">Unable to load this section.</div>';handleError(error)}}}
function collaborationForm(c,editing){const creatorOptions=(state.refs.creatorOptions||[]).map(x=>[x.id,`${x.display_name||x.nickname||'Unnamed'} · ${x.primary_handle?`@${x.primary_handle}`:x.creator_code||''}`]);return`<div class="drawer-section"><h3>${c.stage==='Closed'?'Closed collaboration':'Collaboration details'}</h3><div class="form-grid">${field('collaboration_name','Collaboration Name',c.collaboration_name,editing)}${selectField('creator_id','Creator',creatorOptions,c.creator_id,editing)}${selectField('campaign_id','Campaign',state.refs.campaigns.map(x=>[x.id,x.name]),c.campaign_id,editing)}${selectField('stage','Stage',COLLABORATION_STAGES,c.stage||COLLABORATION_STAGES[0],editing)}${field('type','Type',c.type||'Seeding',editing)}${selectField('owner_id','Owner',state.refs.owners.map(x=>[x.id,x.name]),c.owner_id,editing)}${field('start_date','Start Date',c.start_date,editing,'date')}${field('due_date','Due Date',c.due_date,editing,'date')}${selectField('rights_status','Rights Status',RIGHTS_STATUSES,c.rights_status,editing)}${selectField('payment_status','Payment Status',PAYMENT_STATUSES,c.payment_status,editing)}${field('approved_budget','Approved Budget',c.approved_budget,editing,'number')}${selectField('is_repeat','Repeat Collaboration',[['false','No'],['true','Yes']],String(Boolean(c.is_repeat)),editing,false)}${textarea('notes','Notes',c.notes,editing)}</div></div>`}
async function renderCollaborationRelations(c,tab,body){
  if(tab==='content')return renderContentRelations(c,body);
  if(tab==='products')return renderProductRelations(c,body);
  if(tab==='shipments'){
    const[rows,products]=await Promise.all([related('shipments','collaboration_id',c.id),related('collaboration_products','collaboration_id',c.id,'*,product:products(id,sku,name,category)')]);
    if(!activeDrawer('collaboration',c.id,tab))return;
    body.innerHTML=handoffBanner('Fulfillment handoff','1. Verify the packing list and full address. 2. Pack and ship exactly these items. 3. Add carrier and tracking, then mark the shipment Shipped.')+packingList(products)+relatedEditorSection('shipments','Shipments',rows,row=>row.shipment_code||shortId(row.id,'SH'),row=>`${row.status} · ${ownerName(row.owner_id)} · ${row.carrier||''} ${row.tracking_number||''}`,true);
    bindRelatedRows('shipments',c,rows);return;
  }
  const configs={deliverables:['deliverables','Deliverables',row=>row.type||'Format not agreed',row=>`${row.status} · ${row.platform||'Platform open'} · due ${date(row.due_at)}`],shipments:['shipments','Shipments',row=>row.shipment_code||shortId(row.id,'SH'),row=>`${row.status} · ${ownerName(row.owner_id)} · ${row.carrier||''} ${row.tracking_number||''}`],activity:['activity_logs','Activity',row=>row.action,row=>`${row.entity_type||''} · ${date(row.created_at)}`]};
  const[table,title,primary,secondary]=configs[tab],rows=await related(table,'collaboration_id',c.id,tab==='products'?'*,product:products(id,sku,name)':'*');
  if(!activeDrawer('collaboration',c.id,tab))return;
  const guidance=tab==='shipments'?handoffBanner('Fulfillment handoff','DM owner confirms the saved products and full address. Fulfillment teammate packs exactly that selection, then adds carrier and tracking here.') : '';
  body.innerHTML=guidance+relatedEditorSection(table,title,rows,primary,secondary,tab!=='activity');bindRelatedRows(table,c,rows);
}
async function renderProductRelations(c,body){
  const rows=await related('collaboration_products','collaboration_id',c.id,'*,product:products(id,sku,name,category)');
  if(!activeDrawer('collaboration',c.id,'products'))return;
  const selected=new Set(rows.map(row=>row.product_id)),groups=['Set','Scrunchie','Bandana','Necklace'];
  body.innerHTML=`${handoffBanner('Products to ship','DM owner checks every agreed item and saves once. Fulfillment teammate uses this saved list as the packing instruction.')}
    <div class="drawer-section product-picker"><div class="section-head"><div><h3>Final product selection</h3><p class="muted">Sets and individual items can be combined.</p></div><span id="productSelectionCount" class="status-pill">${selected.size} selected</span></div>
    <div class="product-groups">${groups.map(group=>{const products=state.refs.products.filter(product=>productCategory(product)===group);return`<section class="product-group"><p class="eyebrow">${group}s</p><div class="product-options">${products.map(product=>`<label class="product-option"><input type="checkbox" value="${attr(product.id)}" ${selected.has(product.id)?'checked':''}><span><strong>${esc(product.name)}</strong><small>${esc(product.sku||'')}</small></span></label>`).join('')||'<span class="muted">No products in this group.</span>'}</div></section>`}).join('')}</div>
    <div class="editor-actions"><button id="saveProductSelection" type="button">Save product selection</button></div></div>`;
  $$('.product-option input',body).forEach(input=>input.addEventListener('change',()=>{$('#productSelectionCount').textContent=`${$$('.product-option input:checked',body).length} selected`}));
  $('#saveProductSelection').addEventListener('click',async()=>{const ids=$$('.product-option input:checked',body).map(input=>input.value);setStatus('Saving products');await syncCollaborationProducts(c.id,ids,c.owner_id||null);await logActivity({entityType:'collaboration_products',entityId:c.id,creatorId:c.creator_id,collaborationId:c.id,action:'Product selection updated',after:{product_ids:ids}});setStatus('Ready');toast('Product selection saved');renderCollaborationDrawer()});
}
function productCategory(product){if(product.category)return product.category;const value=`${product.sku||''} ${product.name||''}`.toLowerCase();if(value.includes('set'))return'Set';if(value.includes('scr'))return'Scrunchie';if(value.includes('ban'))return'Bandana';return'Necklace'}
function handoffBanner(title,copy){return`<aside class="handoff-banner"><div><p class="eyebrow">Team handoff</p><strong>${esc(title)}</strong></div><p>${esc(copy)}</p></aside>`}
function packingList(rows){return`<section class="packing-list"><div><p class="eyebrow">Packing list</p><strong>${rows.length?`${rows.length} product${rows.length===1?'':'s'} confirmed`:'Products not confirmed'}</strong></div><div>${rows.length?rows.map(row=>`<span>${esc(row.product?.name||'Unknown product')} <b>×${row.quantity||1}</b></span>`).join(''):'<span class="muted">DM owner must save the final product selection before fulfillment.</span>'}</div></section>`}
async function renderContentRelations(c,body){
  const[publications,assets]=await Promise.all([related('publications','collaboration_id',c.id),related('assets','collaboration_id',c.id)]);
  if(!activeDrawer('collaboration',c.id,'content'))return;body.innerHTML=relatedEditorSection('publications','Published Links',publications,row=>`${row.platform||''} ${row.format||''}`,row=>`${row.status} · ${row.url||'No URL'}`,true)+relatedEditorSection('assets','Creator Assets',assets,row=>row.file_name||row.asset_type||'Asset',row=>row.external_url||row.storage_path||'No link',true);
  bindRelatedRows('publications',c,publications);bindRelatedRows('assets',c,assets);
}
function relatedEditorSection(table,title,rows,primary,secondary,canAdd){return`<div class="drawer-section"><div class="section-head"><h3>${title}</h3>${canAdd?`<button class="secondary compact" data-add-related="${table}" type="button">Add</button>`:''}</div>${rows.length?rows.map(row=>`<article class="related-item"><div><strong>${esc(primary(row)||'Untitled')}</strong><p>${esc(secondary(row)||'')}</p></div>${canAdd?`<button class="secondary compact" data-edit-related="${table}" data-id="${row.id}" type="button">Edit</button>`:''}</article>`).join(''):`<div class="empty-state">No ${title.toLowerCase()} yet.</div>`}</div>`}
function bindRelatedRows(table,c,rows){$$(`[data-add-related="${table}"]`).forEach(button=>button.addEventListener('click',()=>openRelatedEditor(table,c,{})));$$(`[data-edit-related="${table}"]`).forEach(button=>button.addEventListener('click',()=>openRelatedEditor(table,c,rows.find(row=>row.id===button.dataset.id)||{})))}
function openRelatedEditor(table,c,record){const body=$('#drawerBody'),title={collaboration_products:'Product',deliverables:'Deliverable',shipments:'Shipment',publications:'Published Link',assets:'Creator Asset'}[table],guidance=table==='deliverables'?handoffBanner('Deliverable details','Type and platform may stay open until the creator confirms them. Record only what is actually agreed.'):table==='shipments'?handoffBanner('Fulfillment teammate action','Verify the saved products and address, pack the order, then add carrier, tracking and shipment status here.'):'';body.innerHTML=`${guidance}<div class="drawer-section"><div class="section-head"><h3>${record.id?'Edit':'Add'} ${title}</h3><button id="cancelRelated" class="secondary compact" type="button">Cancel</button></div><div id="relatedForm" class="form-grid">${relatedFields(table,record)}</div><div class="editor-actions"><button id="saveRelated" type="button">Save ${title}</button>${record.id?'<button id="archiveRelated" class="secondary" type="button">Archive</button>':''}</div></div>`;$('#cancelRelated').addEventListener('click',()=>renderCollaborationDrawer());$('#saveRelated').addEventListener('click',()=>saveRelatedRecord(table,c,record));$('#archiveRelated')?.addEventListener('click',async()=>{if(!confirm(`Archive this ${title.toLowerCase()}?`))return;await archive(table,record.id);await logActivity({entityType:table,entityId:record.id,creatorId:c.creator_id,collaborationId:c.id,action:'Archived',before:record});renderCollaborationDrawer();toast(`${title} archived`)})}
function relatedFields(table,r){
  if(table==='collaboration_products')return`${selectField('product_id','Product',state.refs.products.map(x=>[x.id,`${x.name} · ${x.sku}`]),r.product_id,true)}${field('quantity','Quantity',r.quantity||1,true,'number')}${selectField('is_primary','Primary Product',[['false','No'],['true','Yes']],String(Boolean(r.is_primary)),true,false)}${textarea('notes','Notes',r.notes,true)}`;
  if(table==='deliverables')return`${field('type','Deliverable Type (optional)',r.type,true)}${field('platform','Platform (optional)',r.platform,true)}${field('quantity','Quantity',r.quantity||1,true,'number')}${selectField('status','Status',DELIVERABLE_STATUSES,r.status||'Pending',true,false)}${field('due_at','Due At',localDateTime(r.due_at),true,'datetime-local')}${field('brief_url','Brief URL',r.brief_url,true,'url')}${textarea('notes','Notes',r.notes,true)}`;
  if(table==='shipments')return`${selectField('owner_id','Fulfillment Owner',state.refs.owners.map(x=>[x.id,x.name]),r.owner_id,true)}${selectField('status','Status',SHIPMENT_STATUSES,r.status||'Draft',true,false)}${field('carrier','Carrier',r.carrier,true)}${field('service_level','Service Level',r.service_level,true)}${field('tracking_number','Tracking Number',r.tracking_number,true)}${field('tracking_url','Tracking URL',r.tracking_url,true,'url')}${field('shipped_at','Shipped At',localDateTime(r.shipped_at),true,'datetime-local')}${field('delivered_at','Delivered At',localDateTime(r.delivered_at),true,'datetime-local')}${textarea('address_snapshot','Full Shipping Address',typeof r.address_snapshot==='object'?r.address_snapshot?.full_address||JSON.stringify(r.address_snapshot):r.address_snapshot,true)}${textarea('exception_notes','Exception Notes',r.exception_notes,true)}`;
  if(table==='publications')return`${field('platform','Platform',r.platform||'Instagram',true)}${field('format','Format',r.format||'Post',true)}${field('url','Published URL',r.url,true,'url')}${selectField('status','Status',PUBLICATION_STATUSES,r.status||'Published',true,false)}${field('published_at','Published At',localDateTime(r.published_at),true,'datetime-local')}${field('views','Views',r.views,true,'number')}${field('likes','Likes',r.likes,true,'number')}${field('comments','Comments',r.comments,true,'number')}${field('shares','Shares',r.shares,true,'number')}${field('saves','Saves',r.saves,true,'number')}${textarea('notes','Performance Notes',r.notes,true)}`;
  return`${field('asset_type','Asset Type',r.asset_type||'Cloud Folder',true)}${field('file_name','Label',r.file_name,true)}${field('external_url','Drive / Asset URL',r.external_url,true,'url')}${selectField('rights_status','Rights Status',RIGHTS_STATUSES,r.rights_status,true)}${textarea('usage_notes','Usage Notes',r.usage_notes,true)}`;
}
async function saveRelatedRecord(table,c,before){const payload=Object.fromEntries(FormDataLike($('#relatedForm')));for(const key of ['quantity','views','likes','comments','shares','saves'])if(payload[key]!=='')payload[key]=Number(payload[key]);for(const key of ['is_primary'])if(key in payload)payload[key]=payload[key]==='true';for(const key of ['due_at','shipped_at','delivered_at','published_at'])if(payload[key]==='')payload[key]=null;if(table==='deliverables'){payload.type=payload.type||null;payload.platform=payload.platform||null}if(table==='shipments')payload.address_snapshot={full_address:payload.address_snapshot||'',source:'CRM v2'};const saved=await save(table,{...before,...payload,collaboration_id:c.id,owner_id:payload.owner_id||before.owner_id||c.owner_id||null});await logActivity({entityType:table,entityId:saved.id,creatorId:c.creator_id,collaborationId:c.id,action:before.id?'Updated':'Created',before:before.id?before:null,after:saved});toast('Saved');renderCollaborationDrawer()}
function openOutreachEditor(creatorId){const body=$('#drawerBody');body.innerHTML=`<div class="drawer-section"><h3>Add outreach touch</h3><div class="form-grid">${selectField('status','Status',OUTREACH_STATUSES,'Contacted',true)}${field('channel','Channel','Instagram DM',true)}${field('last_contact_at','Contacted At',new Date().toISOString().slice(0,16),true,'datetime-local')}${field('next_follow_up_at','Follow-up At','',true,'datetime-local')}${textarea('notes','Notes','',true)}</div><button id="saveOutreachBtn" type="button">Save outreach</button></div>`;$('#saveOutreachBtn').addEventListener('click',async()=>{const payload=Object.fromEntries(FormDataLike(body));await save('outreach_records',{...payload,creator_id:creatorId,owner_id:state.drawer.record.owner_id});toast('Outreach saved');renderCreatorDrawer()})}

async function applyBulkUpdate(){const patch={};if($('#bulkOwner').value)patch.owner_id=$('#bulkOwner').value;if($('#bulkFit').value)patch.fit_verdict=$('#bulkFit').value;if($('#bulkRelationship').value)patch.relationship_status=$('#bulkRelationship').value;if($('#bulkTags').value)patch.tags=$('#bulkTags').value.split(',').map(x=>x.trim()).filter(Boolean);if(!Object.keys(patch).length)return toast('Choose at least one field.');await bulkUpdateCreators([...state.creatorSelection],patch);$('#bulkDialog').close();state.creatorSelection.clear();toast('Bulk update complete');loadCreators()}
function openDrawer(eyebrow,title,subtitle){$('#drawerEyebrow').textContent=eyebrow;$('#drawerTitle').textContent=title;$('#drawerSubtitle').textContent=subtitle;$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false')}
function clearDrawerContent(message='Loading…'){$('#drawerTabs').innerHTML='';$('#drawerBody').innerHTML=`<div class="empty-state">${esc(message)}</div>`;$('#drawerFooter').innerHTML=''}
function closeDrawer(){++state.request.detail;++state.request.drawerRender;$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');state.drawer=null;clearDrawerContent('Select a record to view details.')}
function renderTabs(tabs,active,onClick){$('#drawerTabs').innerHTML=tabs.map(([id,label])=>`<button class="${id===active?'active':''}" data-tab="${id}" type="button">${label}</button>`).join('');$$('#drawerTabs button').forEach(button=>button.addEventListener('click',()=>onClick(button.dataset.tab)))}
function bindDrawerForms(){}
function relationSection(title,rows,primary,secondary){return`<div class="drawer-section"><h3>${title}</h3>${rows.length?rows.map(row=>`<article class="related-item"><div><strong>${esc(primary(row)||'Untitled')}</strong><p>${esc(secondary(row)||'')}</p></div></article>`).join(''):`<div class="empty-state">No ${title.toLowerCase()} yet.</div>`}</div>`}
function field(name,label,value,editing,type='text'){return`<label>${label}<input name="${name}" type="${type}" value="${attr(value)}" ${editing?'':'disabled'}></label>`}
function textarea(name,label,value,editing){return`<label class="wide">${label}<textarea name="${name}" rows="3" ${editing?'':'disabled'}>${esc(value||'')}</textarea></label>`}
function selectField(name,label,options,value,editing,includeBlank=true){const normalized=options.map(x=>Array.isArray(x)?x:[x,x]);if(value&&!normalized.some(([id])=>String(id)===String(value)))normalized.unshift([value,value]);return`<label>${label}<select name="${name}" ${editing?'':'disabled'}>${includeBlank?'<option value="">Select</option>':''}${normalized.map(([id,text])=>`<option value="${attr(id)}" ${String(id)===String(value)?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`}
function setOptions(element,options){if(!element)return;const normalized=options.map(x=>Array.isArray(x)?x:[x,x]);element.innerHTML='<option value="">All</option>'+normalized.map(([id,text])=>`<option value="${attr(id)}">${esc(text)}</option>`).join('')}
function ownerName(id){return state.refs.owners.find(x=>x.id===id)?.name||id||'Unassigned'}
function creatorProfileUrl(savedUrl,handle,platform='Instagram'){const direct=String(savedUrl||'').trim();if(/^https?:\/\//i.test(direct))return direct;const cleanHandle=String(handle||'').trim().replace(/^@/,'');return cleanHandle&&String(platform||'Instagram').toLowerCase().includes('instagram')?`https://www.instagram.com/${encodeURIComponent(cleanHandle)}/`:''}
function profileAction(url){return url?`<a class="profile-link" href="${attr(url)}" target="_blank" rel="noopener noreferrer" title="Open creator Instagram profile" aria-label="Open creator Instagram profile">Open IG</a>`:''}
function bindProfileLinks(root){$$('.profile-link',root).forEach(link=>{link.addEventListener('click',event=>event.stopPropagation());link.addEventListener('dblclick',event=>event.stopPropagation())})}
function activeDrawer(type,id,tab){return state.drawer?.type===type&&state.drawer.record?.id===id&&state.drawerTab===tab}
function shortId(id,prefix){if(!id)return'';return`${prefix}-${String(id).replaceAll('-','').slice(-6).toUpperCase()}`}
function date(value){if(!value)return'—';const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?esc(value):parsed.toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'})}
function localDateTime(value){if(!value)return'';const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?'':new Date(parsed.getTime()-parsed.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function attr(value){return esc(value).replaceAll('`','&#96;')}
function setStatus(text){$('#saveStatus').textContent=text}
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function message(error){try{const parsed=JSON.parse(error.message);return parsed.message||parsed.error_description||error.message}catch{return error.message||String(error)}}
function handleError(error){console.error(error);setStatus('Error');toast(message(error));if(message(error).includes('session expired'))location.reload()}
